"""update column 'token_hash' to 'random_token_hash'

Revision ID: b58e3591280e
Revises: 5ed358c8bfde
Create Date: 2026-09-12 12:11:43.411116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b58e3591280e'
down_revision = '5ed358c8bfde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_verification_token_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('random_token_hash', sa.String(length=64), nullable=False))
        batch_op.create_unique_constraint(
            'uq_email_verification_token_random_token_hash',
            ['random_token_hash']
        )
        batch_op.drop_column('token_hash')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_verification_token_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('token_hash', sa.VARCHAR(length=64), nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('random_token_hash')

    # ### end Alembic commands ###
